export const ADMIN_MODELS = {
  tournament: {
    prismaModel: "tournament",
    label: "Tournament",
    idField: "id",
    idType: "int",
    searchFields: ["title", "game"],
    displayFields: ["id", "title", "game", "status", "startTime"],
    editableFields: [
      "title", "game", "map", "mode", "entryFee", "maxSlots", "status",
      "firstPrize", "secondPrize", "thirdPrize", "killReward", "roomId", "roomPassword",
    ],
  },
  user: {
    prismaModel: "user",
    label: "Player Account",
    idField: "id",
    idType: "int",
    searchFields: ["email", "name", "bgmiIgn", "ffIgn"],
    displayFields: ["id", "name", "email", "crowns", "level"],
    editableFields: ["name", "crowns", "level", "depositWallet", "winningsWallet", "bio"],
  },
  matchHistory: {
    prismaModel: "matchHistory",
    label: "Match Entry",
    idField: "id",
    idType: "int",
    searchFields: ["ign", "uid", "tournamentName", "email"],
    displayFields: ["id", "ign", "tournamentName", "status", "createdAt"],
    editableFields: ["status", "kills", "prizeWon", "rank"],
  },
  walletTransaction: {
    prismaModel: "walletTransaction",
    label: "Wallet Transaction",
    idField: "id",
    idType: "int",
    searchFields: ["description", "type"],
    displayFields: ["id", "amount", "type", "description", "createdAt"],
    editableFields: ["description", "type"],
  },
  withdrawalRequest: {
    prismaModel: "withdrawalRequest",
    label: "Withdrawal Request",
    idField: "id",
    idType: "int",
    searchFields: ["upiId", "status"],
    displayFields: ["id", "amount", "upiId", "status", "createdAt"],
    editableFields: ["status", "amount"],
  },
  notification: {
    prismaModel: "notification",
    label: "Notification",
    idField: "id",
    idType: "string",
    searchFields: ["title", "message"],
    displayFields: ["id", "type", "title", "message", "createdAt"],
    editableFields: ["title", "message", "read"],
  },
  alert: {
    prismaModel: "alert",
    label: "Alert",
    idField: "id",
    idType: "int",
    searchFields: ["title", "message", "type"],
    displayFields: ["id", "type", "severity", "title", "createdAt"],
    editableFields: ["acknowledged", "severity"],
  },
  errorLog: {
    prismaModel: "errorLog",
    label: "Error Log",
    idField: "id",
    idType: "int",
    searchFields: ["route", "message"],
    displayFields: ["id", "route", "message", "createdAt"],
    editableFields: ["alerted"],
  },
  cortexMemory: {
    prismaModel: "cortexMemory",
    label: "Cortex Memory",
    idField: "id",
    idType: "int",
    searchFields: ["fact"],
    displayFields: ["id", "fact", "createdAt"],
    editableFields: ["fact"],
  },
};